[user]
name = "user"
language = "en"
auto_start_server = true

[network]
default_port = 8000
max_connections = 100
connection_timeout_ms = 30000
heartbeat_interval_ms = 60000

[security]
auto_accept_contacts = false
require_encryption = false
allow_anonymous_contacts = false
max_message_size = 1048576

[storage]
data_dir = "./data"
max_chat_history = 1000
auto_cleanup_days = 90
compress_old_messages = false
