name: shadowghost
description: "Decentralized messenger with direct P2P connections. Encrypted messaging, file sharing, and voice calls work without central servers. "
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: 2.11.1
  rust_lib_shadowghost:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  ffigen: ^19.1.0

flutter:
  uses-material-design: true
