[package]
name = "shadowghost"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "shadowghost"
path = "src/bin/main.rs"

[lib]
name = "shadowghost"
path = "src/lib.rs"

[dependencies]
# Async runtime
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.9.5"

# Networking
reqwest = { version = "0.12.23", features = ["json"] }

# Crypto
ring = "0.17"
curve25519-dalek = "4.0"

# Encoding
base64 = "0.22.1"
uuid = { version = "1.0", features = ["v4"] }

# Logging
log = "0.4"
env_logger = "0.11.8"

# Random
rand = "0.9.2"

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# Async utilities
futures = "0.3"

[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.20.0"