[package]
name = "shadowghost"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.0", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
serde_json = "1.0"
base32 = "0.5.1"
toml = "0.9.5"

[lib]
name = "shadowghost"
path = "src/lib.rs"